# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/iot/코드/untitled/menu.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu(object):
    def setupUi(self, menu):
        menu.setObjectName("menu")
        menu.resize(840, 569)
        self.pushButton = QtWidgets.QPushButton(menu)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 281, 531))
        font = QtGui.QFont()
        font.setFamily("ori1Uni")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(menu)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 0, 281, 531))
        font = QtGui.QFont()
        font.setFamily("ori1Uni")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(menu)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 0, 281, 531))
        font = QtGui.QFont()
        font.setFamily("ori1Uni")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(menu)
        self.label.setGeometry(QtCore.QRect(690, 540, 51, 17))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(menu)
        self.label_2.setGeometry(QtCore.QRect(740, 540, 91, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(menu)
        self.label_3.setGeometry(QtCore.QRect(220, 540, 51, 21))
        self.label_3.setObjectName("label_3")
        self.beachlabel = QtWidgets.QLabel(menu)
        self.beachlabel.setGeometry(QtCore.QRect(270, 540, 91, 20))
        self.beachlabel.setText("")
        self.beachlabel.setObjectName("beachlabel")
        self.label_5 = QtWidgets.QLabel(menu)
        self.label_5.setGeometry(QtCore.QRect(370, 540, 31, 21))
        self.label_5.setObjectName("label_5")
        self.guidelabel = QtWidgets.QLabel(menu)
        self.guidelabel.setGeometry(QtCore.QRect(550, 540, 81, 20))
        self.guidelabel.setText("")
        self.guidelabel.setObjectName("guidelabel")
        self.facilitylabel = QtWidgets.QLabel(menu)
        self.facilitylabel.setGeometry(QtCore.QRect(410, 540, 91, 20))
        self.facilitylabel.setText("")
        self.facilitylabel.setObjectName("facilitylabel")
        self.label_8 = QtWidgets.QLabel(menu)
        self.label_8.setGeometry(QtCore.QRect(500, 540, 51, 21))
        self.label_8.setObjectName("label_8")
        self.pushButton_4 = QtWidgets.QPushButton(menu)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 540, 61, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(menu)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 540, 61, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(menu)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 540, 61, 25))
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(menu)
        QtCore.QMetaObject.connectSlotsByName(menu)

    def retranslateUi(self, menu):
        _translate = QtCore.QCoreApplication.translate
        menu.setWindowTitle(_translate("menu", "Dialog"))
        self.pushButton.setText(_translate("menu", "관광지"))
        self.pushButton_2.setText(_translate("menu", "숙박"))
        self.pushButton_3.setText(_translate("menu", "가이드 요청"))
        self.label_2.setText(_translate("menu", "님 환영합니다."))
        self.label_3.setText(_translate("menu", "관광지:"))
        self.label_5.setText(_translate("menu", "숙박:"))
        self.label_8.setText(_translate("menu", "가이드:"))
        self.pushButton_4.setText(_translate("menu", "예약하기"))
        self.pushButton_5.setText(_translate("menu", "예약취소"))
        self.pushButton_6.setText(_translate("menu", "회원탈퇴"))
